
sudo: required

services:
  - docker

before_install:
  - docker build -t darioielardi/docker-react -f Dockerfile.dev .

script:
  - docker run darioielardi/docker-react npm run test -- --coverage   